// Generated by CoffeeScript 2.3.2
var CamerasWidget;

import {
  Widget
} from '/ressources/modules/panel.js';

CamerasWidget = class CamerasWidget extends Widget {
  constructor() {
    super('cameras', 'Cameras');
  }

};

console.log('cameras');

customElements.define('widget-cameras', CamerasWidget);
