# Generated by Django 3.1.2 on 2020-12-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.machine')),
            ],
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('default_value', models.TextField(null=True)),
                ('locked_at', models.DateTimeField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variabletype')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.conditiontype')),
                ('variable1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variable')),
                ('variable2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variable')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('initial', models.BooleanField()),
                ('conditions', models.ManyToManyField(related_name='_state_conditions_+', to='escaperoom.Condition')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.machine')),
            ],
            options={
                'unique_together': {('machine', 'initial')},
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.variable')),
            ],
            options={
                'unique_together': {('timestamp', 'variable')},
            },
        ),
    ]
