# Generated by Django 3.1.2 on 2020-12-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('is_entrypoint', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escaperoom.state')),
            ],
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('default_value', models.TextField(null=True)),
                ('locked_at', models.DateTimeField(null=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escaperoom.operator')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variabletype')),
            ],
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='escaperoom.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='escaperoom.state')),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.state')),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.operatortype'),
        ),
        migrations.AddField(
            model_name='operator',
            name='variable_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variable'),
        ),
        migrations.AddField(
            model_name='operator',
            name='variable_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variable'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.variable')),
            ],
            options={
                'unique_together': {('timestamp', 'variable')},
            },
        ),
    ]
