// Generated by CoffeeScript 2.3.2
import '/interface/scripts/tree.mjs';

import '/interface/scripts/stamp.mjs';

export var onload = function(root) {
  var inspector, tree;
  tree = root.querySelector('*.etcdtree');
  tree.custom_item_modification = (item, data) => {
    // if node doesn't exist in the etcd tree, mark it as ghost
    if (data.node == null) {
      item.classList.add('ghost');
      item.classList.remove('selectable');
    }
    return item;
  };
  inspector = tree.closest('.etcdnav').querySelector('.etcdinspector');
  return tree.onrowselect = (row) => {
    var src;
    // set etcd inspector
    src = 'etcd' + row.getAttribute('item_id') + '?with_values';
    return inspector.src = src;
  };
};
