// Generated by CoffeeScript 2.3.2
var TimerWidget;

import {
  Widget
} from '/ressources/modules/panel.js';

TimerWidget = class TimerWidget extends Widget {
  constructor() {
    super('timer', 'Timer');
  }

};

customElements.define('widget-timer', TimerWidget);
