// Generated by CoffeeScript 2.3.2
(function() {
  var LoadingAnimation,
    boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

  LoadingAnimation = class LoadingAnimation extends HTMLElement {
    constructor() {
      super();
      this.connectedCallback = this.connectedCallback.bind(this);
    }

    connectedCallback() {
      var div, i, j, span;
      boundMethodCheck(this, LoadingAnimation);
      this.innerHTML = '';
      span = document.createElement('span');
      span.classList.add('loading');
      for (i = j = 1; j <= 5; i = ++j) {
        div = document.createElement('div');
        span.appendChild(div);
      }
      return this.appendChild(span);
    }

  };

  customElements.define('loading-animation', LoadingAnimation);

}).call(this);
