# Generated by Django 3.2.4 on 2021-10-17 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='network.node')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('STR', 'string'), ('INT', 'int'), ('FLO', 'float'), ('BOO', 'boolean')], max_length=3)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='network.module')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute', to='engine.variable')),
            ],
        ),
    ]
