// Generated by CoffeeScript 2.3.2
var ActionElement,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

import {
  MultiScreenElement
} from './screen.mjs';

ActionElement = class ActionElement extends MultiScreenElement {
  constructor(default_screen) {
    super(default_screen);
    this.onclick = this.onclick.bind(this);
    this.addEventListener('click', this.onclick);
  }

  onclick() {
    boundMethodCheck(this, ActionElement);
    return console.log('click', this);
  }

};

customElements.define('action-btn', class extends ActionElement {
  constructor() {
    super('loading');
  }

});
