// Generated by CoffeeScript 2.3.2
export var is_empty = function(obj) {
  var key;
  for (key in obj) {
    return false;
  }
  return true;
};

export var sleep = function(ms) {
  return new Promise(function(resolve) {
    return setTimeout(resolve, ms);
  });
};
