// Generated by CoffeeScript 2.3.2
var CluesWidget;

import {
  Widget
} from '/ressources/modules/panel.js';

CluesWidget = class CluesWidget extends Widget {
  constructor() {
    super('clues', 'Clues');
  }

};

customElements.define('widget-clues', CluesWidget);
