// Generated by CoffeeScript 2.3.2
var GameWidget;

import {
  Widget
} from '/ressources/modules/panel.js';

GameWidget = class GameWidget extends Widget {
  constructor() {
    super('game', 'Game');
  }

};

customElements.define('widget-game', GameWidget);
