# Generated by Django 3.1.7 on 2021-03-14 10:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EQU', 'equal'), ('NEQ', 'not equal'), ('GTE', 'greater or equal'), ('LTE', 'lower or equal'), ('GT', 'greater'), ('LT', 'lower'), ('ADD', 'add'), ('SUB', 'substract'), ('MUL', 'multiply'), ('DIV', 'divide')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_entrypoint', models.BooleanField(default=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='escaperoom.state')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='escaperoom.room')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('STR', 'string'), ('INT', 'int'), ('FLO', 'float'), ('BOO', 'boolean'), ('TOG', 'toggle')], max_length=3)),
                ('default_value', models.TextField(null=True)),
                ('locked_at', models.DateTimeField(null=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escaperoom.operator')),
            ],
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='escaperoom.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='escaperoom.state')),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.state')),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='variable_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variable'),
        ),
        migrations.AddField(
            model_name='operator',
            name='variable_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='escaperoom.variable'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escaperoom.variable')),
            ],
        ),
        migrations.AddConstraint(
            model_name='statetransition',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, to_state=django.db.models.expressions.F('from_state')), name='escaperoom_statetransition_different_states'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, parent=django.db.models.expressions.F('id')), name='escaperoom_state_not_own_parent'),
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('timestamp', 'variable')},
        ),
    ]
