// Generated by CoffeeScript 2.3.2
var StoryWidget;

import {
  Widget
} from '/ressources/modules/panel.js';

StoryWidget = class StoryWidget extends Widget {
  constructor() {
    super('story', 'Story');
  }

};

customElements.define('widget-story', StoryWidget);
