// Generated by CoffeeScript 2.3.2
var CluesBox,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

import {
  Subscriber,
  Container
} from './monitor.js';

import {
  is_empty,
  post_control
} from './monitor.js';

CluesBox = class CluesBox extends HTMLElement {
  constructor() {
    super();
    this.send_clue = this.send_clue.bind(this);
    this.querySelector('button').onclick = this.send_clue;
  }

  send_clue(event) {
    var text;
    boundMethodCheck(this, CluesBox);
    text = event.target.parentNode.querySelector('textarea').value;
    return post_control('/display', {
      action: 'clue',
      text: text
    });
  }

};

customElements.define('clues-box', CluesBox);
