// Generated by CoffeeScript 2.3.2
var CluesBox,
  boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

import {
  Subscriber,
  Container
} from './monitor.js';

import {
  is_empty
} from './monitor.js';

CluesBox = class CluesBox extends HTMLElement {
  constructor() {
    super();
    this.send_clue = this.send_clue.bind(this);
    this.querySelector('button').onclick = this.send_clue;
  }

  async send_clue(event) {
    var reponse, text;
    boundMethodCheck(this, CluesBox);
    text = event.target.parentNode.querySelector('textarea').value;
    return reponse = (await fetch('/display?name=clues', {
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        type: 'clue',
        text: text
      }),
      method: 'POST'
    }));
  }

};

customElements.define('clues-box', CluesBox);
