# Generated by Django 3.2.4 on 2021-10-17 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escaperoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EQU', 'equal'), ('NEQ', 'not equal'), ('GTE', 'greater or equal'), ('LTE', 'lower or equal'), ('GT', 'greater'), ('LT', 'lower'), ('ADD', 'add'), ('SUB', 'substract'), ('MUL', 'multiply'), ('DIV', 'divide')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('is_entrypoint', models.BooleanField(default=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='engine.state')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='escaperoom.room')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('type', models.CharField(choices=[('STR', 'string'), ('INT', 'int'), ('FLO', 'float'), ('BOO', 'boolean'), ('TOG', 'toggle')], max_length=3)),
                ('default_value', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.operator')),
            ],
        ),
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.ManyToManyField(related_name='_engine_statetransition_conditions_+', to='engine.Variable')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='engine.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='engine.state')),
            ],
        ),
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.state')),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='variable_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='engine.variable'),
        ),
        migrations.AddField(
            model_name='operator',
            name='variable_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='engine.variable'),
        ),
        migrations.CreateModel(
            name='VariableChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.variable')),
            ],
            options={
                'unique_together': {('timestamp', 'variable')},
            },
        ),
        migrations.AddConstraint(
            model_name='statetransition',
            constraint=models.CheckConstraint(check=models.Q(('to_state', django.db.models.expressions.F('from_state')), _negated=True), name='engine_statetransition_different_states'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.CheckConstraint(check=models.Q(('parent', django.db.models.expressions.F('id')), _negated=True), name='engine_state_not_own_parent'),
        ),
    ]
