import {MultiScreenElement} from '/modules/screen.mjs'

// Generated by CoffeeScript 2.3.2
export var main = function() {
  return console.log('*-* main *-*');
};

console.log('*-* module *-*', MultiScreenElement);
