// Generated by CoffeeScript 2.3.2
import '/interface/scripts/list.mjs';

import '/interface/scripts/action.mjs';

export var onload = function(root) {
  var list;
  list = root.querySelector("synced-list");
  return list.custom_update = function(item, data) {
    var btn;
    if (data.active) {
      item.removeAttribute('disabled');
    } else {
      item.setAttribute('disabled', '');
    }
    btn = item.querySelector('action-btn');
    if (data.registered) {
      btn.set_screen('checked');
    } else {
      btn.set_screen('unchecked');
    }
    return data;
  };
};
