// Generated by CoffeeScript 2.3.2
import '/interface/scripts/list.mjs';

import '/interface/scripts/stamp.mjs';

export var onload = function(root) {
  var list;
  list = root.querySelector("synced-list");
  return list.custom_update = function(item, data) {
    var button;
    if (data.active) {
      item.removeAttribute('disabled');
    } else {
      item.setAttribute('disabled', '');
    }
    button = item.querySelector('stamp-button');
    if (data.registered) {
      button.set_screen('checked');
    } else {
      button.set_screen('unchecked');
    }
    return data;
  };
};
